import { expect, test } from "@playwright/test";
import { readdirSync } from "node:fs";
import path from "node:path";

test("March exports: real upload, normalization, reconciliation and live AI", async ({ page }) => {
  test.skip(process.env.FINTRACE_LIVE_E2E !== "1", "Explicit live API/provider opt-in");
  test.setTimeout(240_000);
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("/login");
  await page.getByRole("button", { name: "Continue to FinTrace" }).click();
  await expect(page).not.toHaveURL(/login/);
  await page.goto("/investigations/new");
  await page.getByLabel("Close name", { exact: true }).fill("March 2026 Final Validation");
  await page.getByLabel("Period start").fill("2026-03-01");
  await page.getByLabel("Period end").fill("2026-03-31");
  await page.getByRole("button", { name: "Create close", exact: true }).click();
  await expect(page).toHaveURL(/investigations\/FIN-.+\/data/);
  const dataUrl = page.url();
  console.log("Validated close:", dataUrl);
  await page.screenshot({ path: "test-results/march-01-created.png", fullPage: true });
  const folder = path.resolve("systhantic data/March_2026");
  const files = readdirSync(folder).filter(f => /\.(xlsx|csv)$/.test(f)).map(f => path.join(folder, f));
  expect(files).toHaveLength(7);
  await page.locator('input[type="file"]').setInputFiles(files);
  await expect(page.getByText("✓ All files understood", { exact: true })).toBeVisible({ timeout: 100_000 });
  await expect(page.getByRole("button", { name: "Run close", exact: true })).toBeEnabled({ timeout: 100_000 });
  await page.screenshot({ path: "test-results/march-02-uploaded.png", fullPage: true });
  // Successful identical files must not become duplicate sources.
  await page.locator('input[type="file"]').setInputFiles(files);
  await expect(page.getByText("Understanding files…")).toHaveCount(0, { timeout: 60_000 });
  await expect(page.getByText("7 files · Everything understood", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Run close", exact: true }).click();
  await expect(page).toHaveURL(/reconciliation/, { timeout: 90_000 });
  await expect(page.getByText("515 / 515 records accounted for")).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText("Needs attention", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/march-03-results.png", fullPage: true });
  const ambiguous = page.getByRole("link").filter({ hasText: "Ambiguous Association" }).first();
  await expect(ambiguous).toBeVisible();
  await ambiguous.click();
  await expect(page.getByText("Records from this close’s uploaded dataset.", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Investigate evidence", exact: true }).click();
  await expect(page.getByText("AI assessment · groq", { exact: false })).toBeVisible({ timeout: 90_000 });
  await expect(page.getByText("Evidence confidence", { exact: false })).toBeVisible();
  await expect(page.getByRole("button", { name: "Retry AI investigation" })).toHaveCount(0);
  await page.screenshot({ path: "test-results/march-04-live-ai.png", fullPage: true });
  console.log("Live AI case:", page.url());
  await page.getByRole("button", { name: "Back to results" }).click();
  const inventory = page.getByRole("link").filter({ hasText: "Inventory" }).first();
  await inventory.click();
  await expect(page.getByText("Inventory · Sale", { exact: true })).toBeVisible();
  await expect(page.getByText("SKU", { exact: false }).first()).toBeVisible();
  await page.getByRole("button", { name: "Investigate evidence", exact: true }).click();
  await expect(page.getByText("AI assessment · groq", { exact: false })).toBeVisible({ timeout: 90_000 });
  await expect(page.getByRole("button", { name: "Retry AI investigation" })).toHaveCount(0);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "test-results/march-05-inventory.png", fullPage: true });
  await page.getByRole("button", { name: "Back to results" }).click();
  await page.getByRole("link").filter({ hasText: "Inventory Quantity Mismatch" }).first().click();
  await expect(page.getByText("Inventory · Sale", { exact: true })).toBeVisible();
  await expect(page.getByText("Inventory · Return", { exact: true })).toBeVisible();
  const response = page.waitForResponse(r => r.url().endsWith("/investigate") && r.request().method() === "POST");
  await page.getByRole("button", { name: "Investigate evidence", exact: true }).click();
  const assessment = await (await response).json();
  expect(assessment.provider).toBe("groq");
  expect(assessment.verifier_passed).toBe(true);
  expect(assessment.status).toBe("SUPPORTED");
  await expect(page.getByText("Evidence confidence", { exact: true })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "test-results/march-06-quantity-ai.png", fullPage: true });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "March 2026 Final Validation", exact: true })).toBeVisible();
  await expect(page.getByText("515 / 515 records accounted for")).toBeVisible();
  await expect(page.getByText("Needs attention", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/march-07-home-latest.png", fullPage: true });
  expect(errors).toEqual([]);
});
