"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, CalendarDays, Check, ChevronRight, CircleAlert, Clock3, Download, ExternalLink, Filter, LockKeyhole, MoreHorizontal, Play, RefreshCw, Search, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { Button, Card, CardContent, CardHeader, CardTitle, Progress } from "@fintrace/ui";
import { appConfig, exceptionItems, formatCurrency, healthBreakdown, metrics, patterns, recentRuns } from "../lib/data";
import type { ExceptionItem } from "../lib/types";
import { SeverityBadge, StatusBadge } from "./status-badge";

const bars = [38, 44, 40, 54, 48, 62, 58, 76, 64, 72, 82, 68, 86, 78, 94, 88, 100, 92, 74, 80, 68, 70, 61, 66, 59, 55, 58, 51, 48, 44];

export function PageHeading({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: React.ReactNode }) {
  return <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-slate-400"><span>{eyebrow}</span><span className="h-1 w-1 rounded-full bg-slate-300" />{appConfig.batchName}</div><h1 className="text-[28px] font-bold tracking-[-0.03em] text-slate-950">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{description}</p></div><div className="flex items-center gap-2">{children}</div></div>;
}

function MetricCard({ label, value, detail, trend, tone }: typeof metrics[number]) {
  const positive = tone === "positive" || trend?.startsWith("+");
  return <Card className="min-w-0"><CardContent className="p-5"><div className="flex items-start justify-between gap-2"><span className="text-xs font-medium text-slate-500">{label}</span>{trend && <span className={`flex items-center gap-0.5 text-[11px] font-bold ${positive ? "text-emerald-600" : tone === "critical" ? "text-rose-600" : "text-amber-600"}`}>{positive ? <ArrowUpRight className="h-3 w-3" /> : <ArrowDownRight className="h-3 w-3" />}{trend}</span>}</div><div className="mt-3 text-[25px] font-bold tracking-tight text-slate-950">{value}</div><div className="mt-1 text-[11px] text-slate-400">{detail}</div></CardContent></Card>;
}

function HealthCard() {
  return <Card className="lg:col-span-5"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Reconciliation health</CardTitle><p className="mt-1 text-xs text-slate-400">Across the current batch</p></div><button className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100"><MoreHorizontal className="h-4 w-4" /></button></CardHeader><CardContent><div className="mb-5 flex h-3 overflow-hidden rounded-full bg-slate-100">{healthBreakdown.map(item => <div key={item.label} className={item.tone} style={{ width: `${item.percent}%` }} />)}</div><div className="grid grid-cols-2 gap-x-6 gap-y-4">{healthBreakdown.map(item => <div key={item.label} className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs text-slate-500"><span className={`h-2 w-2 rounded-full ${item.tone}`} />{item.label}</div><span className="text-xs font-bold text-slate-800">{item.value.toLocaleString()}</span></div>)}</div><div className="mt-6 border-t border-slate-100 pt-4"><div className="flex items-center justify-between text-xs"><span className="font-medium text-slate-600">Auto-reconciliation rate</span><span className="font-bold text-emerald-600">86.7%</span></div><Progress value={86.7} className="mt-2" /></div></CardContent></Card>;
}

function ThroughputCard() {
  return <Card className="lg:col-span-7"><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Processing throughput</CardTitle><p className="mt-1 text-xs text-slate-400">Records reconciled · last 30 runs</p></div><div className="flex items-center gap-1 rounded-md border border-slate-200 px-2 py-1 text-[11px] font-medium text-slate-500"><CalendarDays className="h-3.5 w-3.5" />30 days</div></CardHeader><CardContent><div className="flex items-end justify-between"><div><span className="text-[26px] font-bold tracking-tight text-slate-950">428</span><span className="ml-2 text-xs text-slate-400">records / second</span><div className="mt-1 flex items-center gap-1 text-[11px] font-semibold text-emerald-600"><TrendingUp className="h-3 w-3" />12.4% vs previous period</div></div><div className="rounded-md bg-emerald-50 px-2 py-1 text-[11px] font-semibold text-emerald-700">Healthy</div></div><div className="mt-6 flex h-[88px] items-end gap-1.5">{bars.map((height, index) => <div key={index} className="group relative flex-1"><div className={`w-full rounded-t-sm transition-colors group-hover:bg-slate-900 ${index > 25 ? "bg-slate-200" : "bg-slate-300"}`} style={{ height: `${height}%` }} /></div>)}</div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>01 Aug</span><span>15 Aug</span><span>30 Aug</span></div></CardContent></Card>;
}

function ExceptionQueue({ items = exceptionItems, compact = false }: { items?: ExceptionItem[]; compact?: boolean }) {
  return <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{compact ? "Priority exceptions" : "Exception queue"}</CardTitle><p className="mt-1 text-xs text-slate-400">{compact ? "The incidents requiring attention first" : "All unresolved lifecycle breaks in this run"}</p></div><div className="flex items-center gap-2"><button className="hidden rounded-md border border-slate-200 p-2 text-slate-500 hover:bg-slate-50 sm:block"><Filter className="h-3.5 w-3.5" /></button><Link href="/exceptions" className="flex items-center gap-1 text-xs font-semibold text-slate-700 hover:text-slate-950">View all <ChevronRight className="h-3.5 w-3.5" /></Link></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-y border-slate-100 bg-slate-50/70 text-[10px] font-bold uppercase tracking-[0.13em] text-slate-400"><th className="px-5 py-3 font-bold">Exception</th><th className="px-3 py-3 font-bold">Severity</th><th className="px-3 py-3 font-bold">Status</th><th className="px-3 py-3 font-bold">Exposure</th><th className="px-3 py-3 font-bold">Detected</th><th className="px-5 py-3" /></tr></thead><tbody>{items.slice(0, compact ? 4 : 10).map(item => <tr key={item.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/70"><td className="px-5 py-3.5"><Link href={`/exceptions/${item.id}`} className="group block"><div className="flex items-center gap-2"><span className="font-mono text-[10px] text-slate-400">{item.id}</span><span className="text-xs font-semibold text-slate-800 group-hover:text-slate-950">{item.label}</span></div><div className="mt-1 flex items-center gap-1.5 text-[11px] text-slate-400"><span>{item.orderId}</span><span>·</span><span>{item.source}</span></div></Link></td><td className="px-3 py-3.5"><SeverityBadge severity={item.severity} /></td><td className="px-3 py-3.5"><StatusBadge status={item.status} /></td><td className="px-3 py-3.5 text-xs font-semibold text-slate-700">{formatCurrency(item.exposure)}</td><td className="px-3 py-3.5 text-xs text-slate-500">{item.detectedAt}</td><td className="px-5 py-3.5 text-right"><Link href={`/exceptions/${item.id}`} className="inline-flex rounded p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><ChevronRight className="h-4 w-4" /></Link></td></tr>)}</tbody></table></div></CardContent></Card>;
}

export function Overview() {
  return <><PageHeading eyebrow="Control center" title="Good afternoon, Aarav" description="A clear view of financial integrity across your transaction lifecycles."><Button variant="outline" size="sm"><Download className="h-3.5 w-3.5" />Export report</Button><Button size="sm"><RefreshCw className="h-3.5 w-3.5" />Run reconciliation</Button></PageHeading><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(metric => <MetricCard key={metric.label} {...metric} />)}</div><div className="mb-6 grid gap-4 lg:grid-cols-12"><HealthCard /><ThroughputCard /></div><div className="mb-6"><ExceptionQueue compact /></div><div className="grid gap-4 lg:grid-cols-12"><Card className="lg:col-span-7"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Recurring patterns</CardTitle><p className="mt-1 text-xs text-slate-400">Signals found across related exceptions</p></div><Link href="/patterns" className="text-xs font-semibold text-slate-700">See patterns <ChevronRight className="inline h-3.5 w-3.5" /></Link></CardHeader><CardContent className="space-y-4">{patterns.slice(0, 2).map(pattern => <div key={pattern.id} className="flex items-start gap-3 rounded-lg border border-slate-100 p-3.5"><div className="mt-0.5 rounded-md bg-rose-50 p-2 text-rose-600"><CircleAlert className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-semibold text-slate-800">{pattern.title}</div><SeverityBadge severity={pattern.severity} /></div><p className="mt-1 text-[11px] leading-5 text-slate-500">{pattern.description}</p><div className="mt-2 flex gap-4 text-[10px] text-slate-400"><span><strong className="text-slate-700">{pattern.incidents}</strong> incidents</span><span><strong className="text-slate-700">{formatCurrency(pattern.exposure)}</strong> exposure</span><span>{pattern.location}</span></div></div></div>)}</CardContent></Card><Card className="lg:col-span-5"><CardHeader><CardTitle>Control posture</CardTitle><p className="mt-1 text-xs text-slate-400">Guardrails are active for this workspace</p></CardHeader><CardContent className="space-y-4">{[{icon: ShieldCheck, title: "Deterministic matching", detail: "No AI in financial calculations", tone: "text-emerald-600 bg-emerald-50"}, {icon: LockKeyhole, title: "Approval gates", detail: "High-value actions require review", tone: "text-indigo-600 bg-indigo-50"}, {icon: Sparkles, title: "Evidence-bounded AI", detail: "Read-only investigation tools", tone: "text-violet-600 bg-violet-50"}].map(item => <div key={item.title} className="flex items-center gap-3"><div className={`rounded-md p-2 ${item.tone}`}><item.icon className="h-4 w-4" /></div><div><div className="text-xs font-semibold text-slate-800">{item.title}</div><div className="mt-0.5 text-[11px] text-slate-400">{item.detail}</div></div><Check className="ml-auto h-4 w-4 text-emerald-500" /></div>)}</CardContent></Card></div></>;
}

export function ExceptionsPage() {
  const [query, setQuery] = React.useState("");
  const [severity, setSeverity] = React.useState("ALL");
  const [status, setStatus] = React.useState("ALL");
  const filtered = exceptionItems.filter(item => `${item.id} ${item.orderId} ${item.label}`.toLowerCase().includes(query.toLowerCase()) && (severity === "ALL" || item.severity === severity) && (status === "ALL" || item.status === status));
  return <><PageHeading eyebrow="Exceptions" title="Exception queue" description="Investigate the lifecycle breaks that deterministic reconciliation could not safely close."><Button variant="outline" size="sm"><Download className="h-3.5 w-3.5" />Export queue</Button></PageHeading><div className="mb-4 flex flex-col gap-2 rounded-xl border border-slate-200 bg-white p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search exception ID, order or type" className="h-9 w-full rounded-md border border-slate-200 bg-slate-50 pl-9 pr-3 text-xs outline-none focus:border-slate-400" /></div><select value={severity} onChange={event => setSeverity(event.target.value)} className="h-9 rounded-md border border-slate-200 bg-white px-3 text-xs text-slate-600 outline-none"><option value="ALL">All severity</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option></select><select value={status} onChange={event => setStatus(event.target.value)} className="h-9 rounded-md border border-slate-200 bg-white px-3 text-xs text-slate-600 outline-none"><option value="ALL">All status</option><option value="OPEN">Open</option><option value="IN_REVIEW">In review</option><option value="ESCALATED">Escalated</option><option value="RESOLVED">Resolved</option></select></div><Card><CardContent className="p-0"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="text-xs text-slate-500"><span className="font-semibold text-slate-800">{filtered.length}</span> visible in demo queue</div><div className="flex items-center gap-2 text-[11px] text-slate-400"><Clock3 className="h-3.5 w-3.5" />Sorted by severity and age</div></div><ExceptionTable items={filtered} /></CardContent></Card></>;
}

function ExceptionTable({ items }: { items: ExceptionItem[] }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/70 text-[10px] font-bold uppercase tracking-[0.13em] text-slate-400"><th className="px-5 py-3">Exception</th><th className="px-3 py-3">Severity</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Exposure</th><th className="px-3 py-3">Owner</th><th className="px-3 py-3">Detected</th><th className="px-5 py-3" /></tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/70"><td className="px-5 py-3.5"><Link href={`/exceptions/${item.id}`} className="group block"><div className="flex items-center gap-2"><span className="font-mono text-[10px] text-slate-400">{item.id}</span><span className="text-xs font-semibold text-slate-800 group-hover:text-slate-950">{item.label}</span></div><div className="mt-1 flex items-center gap-1.5 text-[11px] text-slate-400"><span>{item.orderId}</span><span>·</span><span>{item.summary}</span></div></Link></td><td className="px-3 py-3.5"><SeverityBadge severity={item.severity} /></td><td className="px-3 py-3.5"><StatusBadge status={item.status} /></td><td className="px-3 py-3.5 text-xs font-semibold text-slate-700">{formatCurrency(item.exposure)}</td><td className="px-3 py-3.5 text-xs text-slate-500">{item.assignee}</td><td className="px-3 py-3.5 text-xs text-slate-500">{item.detectedAt}</td><td className="px-5 py-3.5 text-right"><Link href={`/exceptions/${item.id}`} className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-2 py-1.5 text-[11px] font-semibold text-slate-600 hover:bg-slate-50">Inspect <ExternalLink className="h-3 w-3" /></Link></td></tr>)}</tbody></table>{items.length === 0 && <div className="py-20 text-center"><div className="text-sm font-semibold text-slate-700">No exceptions match these filters</div><p className="mt-1 text-xs text-slate-400">Try widening the search or clearing a filter.</p></div>}</div>;
}

export function PatternsPage() {
  return <><PageHeading eyebrow="Patterns" title="Recurring operational signals" description="Clusters of related exceptions can point to a control gap. They are signals for review, not proof of causation."><Button variant="outline" size="sm"><Download className="h-3.5 w-3.5" />Export patterns</Button></PageHeading><div className="mb-5 grid gap-4 sm:grid-cols-3"><MetricCard label="Active patterns" value="7" detail="Across 133 exceptions" tone="neutral" /><MetricCard label="Associated exposure" value="₹1,33,560" detail="28% of open exposure" tone="warning" /><MetricCard label="Highest concentration" value="BLR-03" detail="12 incidents · manual refund" tone="critical" /></div><div className="grid gap-4">{patterns.map(pattern => <Card key={pattern.id}><CardContent className="flex flex-col gap-5 p-5 md:flex-row md:items-center"><div className="flex min-w-0 flex-1 items-start gap-3"><div className="rounded-lg bg-rose-50 p-2.5 text-rose-600"><CircleAlert className="h-5 w-5" /></div><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] text-slate-400">{pattern.id}</span><SeverityBadge severity={pattern.severity} /><h3 className="basis-full text-sm font-semibold text-slate-900 md:basis-auto">{pattern.title}</h3></div><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-500">{pattern.description}</p></div></div><div className="grid grid-cols-3 gap-6 border-t border-slate-100 pt-4 text-xs md:border-l md:border-t-0 md:pl-6 md:pt-0"><div><div className="text-[10px] uppercase tracking-wide text-slate-400">Incidents</div><div className="mt-1 font-bold text-slate-800">{pattern.incidents}</div></div><div><div className="text-[10px] uppercase tracking-wide text-slate-400">Exposure</div><div className="mt-1 font-bold text-slate-800">{formatCurrency(pattern.exposure)}</div></div><div><div className="text-[10px] uppercase tracking-wide text-slate-400">Location</div><div className="mt-1 font-bold text-slate-800">{pattern.location}</div></div></div><div className="rounded-lg bg-slate-50 p-3 md:w-[270px]"><div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-slate-400"><ShieldCheck className="h-3.5 w-3.5" />Suggested control</div><p className="mt-1.5 text-[11px] leading-4 text-slate-600">{pattern.control}</p></div></CardContent></Card>)}</div></>;
}

export function RunsPage() { return <><PageHeading eyebrow="Controls" title="Reconciliation runs" description="A reproducible history of each batch processed through the deterministic engine."><Button size="sm"><Play className="h-3.5 w-3.5" />Start new run</Button></PageHeading><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/70 text-[10px] font-bold uppercase tracking-[0.13em] text-slate-400"><th className="px-5 py-3">Run</th><th className="px-3 py-3">Records</th><th className="px-3 py-3">Match rate</th><th className="px-3 py-3">Exceptions</th><th className="px-3 py-3">Completed</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{recentRuns.map(run => <tr key={run.name} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4 text-xs font-semibold text-slate-800">{run.name}<div className="mt-1 font-mono text-[10px] text-slate-400">seed 42 · deterministic</div></td><td className="px-3 py-4 text-xs text-slate-600">{run.records}</td><td className="px-3 py-4 text-xs font-semibold text-emerald-600">{run.match}</td><td className="px-3 py-4 text-xs text-slate-600">{run.exceptions}</td><td className="px-3 py-4 text-xs text-slate-500">{run.completed}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />{run.status}</span></td></tr>)}</tbody></table></div></CardContent></Card></>; }

export function EvaluationsPage() { return <><PageHeading eyebrow="Controls" title="Evaluation & reliability" description="Metrics are computed against hidden synthetic ground truth so the benchmark stays honest and reproducible."><Button variant="outline" size="sm"><RefreshCw className="h-3.5 w-3.5" />Run evaluation</Button></PageHeading><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{label:"Match precision", value:"99.1%", detail:"Safe automatic matches"}, {label:"Exception recall", value:"93.4%", detail:"Actual breaks detected"}, {label:"Escalation accuracy", value:"97.1%", detail:"Ambiguous cases routed"}, {label:"Unsafe resolutions", value:"0", detail:"Target is zero"}].map(item => <MetricCard key={item.label} {...item} tone={item.value === "0" ? "positive" : "neutral"} />)}</div><Card className="mt-4"><CardHeader><CardTitle>Benchmark notes</CardTitle></CardHeader><CardContent className="space-y-3 text-xs leading-5 text-slate-500"><p>Current demo figures represent the seeded August close benchmark. Root-cause accuracy is measured only for investigated labeled exceptions; latency and throughput are reported separately.</p><div className="flex items-center gap-2 rounded-md bg-emerald-50 px-3 py-2.5 font-medium text-emerald-800"><ShieldCheck className="h-4 w-4" /> No claims are made about production performance from synthetic data.</div></CardContent></Card></>; }

export function AuditPage() { return <><PageHeading eyebrow="Controls" title="Audit trail" description="Append-only activity across investigations, approvals, and policy-bound actions."><Button variant="outline" size="sm"><Download className="h-3.5 w-3.5" />Export log</Button></PageHeading><Card><CardContent className="p-0"><div className="divide-y divide-slate-100">{[...exceptionItems, ...exceptionItems.slice(0, 2)].map((item, index) => <div key={`${item.id}-${index}`} className="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3 sm:w-[185px]"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-100 text-slate-500"><ShieldCheck className="h-3.5 w-3.5" /></div><span className="font-mono text-[10px] text-slate-400">{index < 4 ? "12:04:20" : "11:42:08"}</span></div><div className="flex-1"><div className="text-xs font-semibold text-slate-800">{index % 2 === 0 ? "EXCEPTION_CREATED" : "INVESTIGATION_STARTED"}</div><div className="mt-1 text-[11px] text-slate-400">{item.id} · {item.orderId} · {index % 2 === 0 ? "FinTrace rules" : "Aarav Mehta"}</div></div><span className="text-[11px] text-slate-500">{index % 2 === 0 ? "4 rules triggered" : "Bounded evidence collection"}</span></div>)}</div></CardContent></Card></>; }

export function SettingsPage() { return <><PageHeading eyebrow="Workspace" title="Settings" description="Workspace configuration and policy controls for Northstar Retail Group." /><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Workspace details</CardTitle></CardHeader><CardContent className="space-y-4">{[["Workspace name", appConfig.workspaceName], ["Environment", "Production workspace"], ["Currency", "INR · Indian Rupee"], ["Dataset mode", "Synthetic demo data"]].map(row => <div key={row[0]} className="flex items-center justify-between border-b border-slate-100 pb-3 last:border-0 last:pb-0"><span className="text-xs text-slate-500">{row[0]}</span><span className="text-xs font-semibold text-slate-800">{row[1]}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Approval policy</CardTitle></CardHeader><CardContent className="space-y-4">{[["₹0–₹10,000", "Finance Manager"], ["₹10,001–₹1,00,000", "Controller"], [">₹1,00,000", "Controller + secondary approval"]].map(row => <div key={row[0]} className="flex items-center justify-between border-b border-slate-100 pb-3 last:border-0 last:pb-0"><span className="font-mono text-xs text-slate-500">{row[0]}</span><span className="text-xs font-semibold text-slate-800">{row[1]}</span></div>)}</CardContent></Card></div></>; }
