import Link from "next/link";
import { ArrowRight, BookOpen, FileSpreadsheet, ShieldCheck, UploadCloud, Workflow } from "lucide-react";
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@fintrace/ui";
import { PageHeading } from "./dashboard";

const sourceFiles = [
  ["August_Orders.xlsx", "Orders", "Start each transaction lifecycle.", "ReceiptNo, OutletCode, SaleValue, SaleTimestamp, OrderStatus"],
  ["Gateway_Payments.csv", "Payments", "Connect captured money to an order.", "GatewayTxn, ReceiptReference, PaidValue, CapturedWhen, PaymentState"],
  ["Bank_Settlement_Report.xlsx", "Settlements", "Check money received after gateway fees.", "SettlementRef, GatewayReference, GrossPaid, ProcessingFee, NetSettled, BookedAt"],
  ["ERP_Invoice_Register.csv", "Invoices", "Check the ERP invoice and amount.", "DocumentNo, ReceiptLink, InvoiceTotal, InvoiceState, PostedDate"],
  ["Refund_Report.xlsx", "Refunds", "Check money returned to the customer.", "RefundReference, OriginalGatewayTxn, RefundedValue, RefundState, ProcessedAt"],
  ["Inventory_Movements.csv", "Inventory movements", "Check sale and return movements.", "MovementReference, ReceiptReference, MovementType, Quantity, RecordedAt"],
  ["Employee_Actions.csv", "Employee actions", "Add operational context to a lifecycle.", "ActionReference, EntityType, ReceiptReference, EmployeeCode, Operation"],
] as const;

const roleGuides = [
  ["Analyst", "Prepare and explain the close", "Upload exports, review uncertain mappings and relationships, run reconciliation, inspect lifecycles, and investigate eligible cases. You can request a decision but cannot approve it or read restricted audit data."],
  ["Finance Manager", "Review and approve eligible actions", "Work the same close queue, assess evidence, and approve eligible low-value actions when policy allows. Patterns and Audit show recurring signals and recorded decisions."],
  ["Controller", "Own the close sign-off", "Review the full close, decide ambiguous cases, approve escalated requests, and sign off with Patterns, Evaluations, and Audit available."],
] as const;

function Step({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return <div className="flex gap-3"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">{number}</div><div><div className="text-sm font-semibold text-foreground">{title}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">{children}</p></div></div>;
}

export function GuidePage() {
  return <>
    <PageHeading eyebrow="How to use FinTrace" title="Close a financial period" description="Use FinTrace to reconcile a month, understand what happened, and work only the cases that need evidence, a human decision, or approval." />
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1.3fr)_minmax(280px,0.7fr)]">
      <Card>
        <CardContent className="space-y-5"><Step number={1} title="Enter the close workspace">Continue to FinTrace opens the Controller workspace. Other sample roles are available only when you need to show RBAC handoff.</Step><Step number={2} title="Start or open a close">Open Closes and choose an existing close, or create one with a name, period, and currency.</Step><Step number={3} title="Load source exports">Open Data and upload the seven CSV/XLSX exports together. FinTrace profiles and proposes mappings after upload.</Step><Step number={4} title="Review only uncertainty">High-confidence setup can be accepted automatically. Review incomplete mappings, unfamiliar fields, or conflicting source relationships.</Step><Step number={5} title="Run the close">Choose Run close from Data. FinTrace accounts for every normalized record, reconstructs lifecycles, and produces deterministic outcomes.</Step><Step number={6} title="Work the attention queue">Open an explained finding to see what happened without running AI. Use the bounded evidence check only when evidence is missing; ambiguous reference gaps remain NEEDS EVIDENCE.</Step><Step number={7} title="Separate decision from approval">A human decision is reserved for evidence-backed policy choices. Approval is a separate control for consequential actions. Audit records the close and its decisions.</Step></CardContent>
      </Card>
      <Card>
        <CardHeader><CardTitle>What you are showing</CardTitle></CardHeader>
        <CardContent className="space-y-4 text-xs"><div className="flex gap-3"><Workflow className="h-4 w-4 shrink-0 text-primary" /><p className="leading-5 text-muted-foreground"><span className="font-semibold text-foreground">Deterministic truth:</span> FinTrace normalizes records, connects lifecycles, reconciles money, and identifies exceptions.</p></div><div className="flex gap-3"><BookOpen className="h-4 w-4 shrink-0 text-primary" /><p className="leading-5 text-muted-foreground"><span className="font-semibold text-foreground">Evidence investigation:</span> The provider retrieves only relevant read-only records and returns a structured conclusion.</p></div><div className="flex gap-3"><ShieldCheck className="h-4 w-4 shrink-0 text-primary" /><p className="leading-5 text-muted-foreground"><span className="font-semibold text-foreground">Human control:</span> Supported conclusions can still require approval; ambiguous cases stay unresolved and are escalated.</p></div><Button asChild className="w-full"><Link href="/investigations">Open investigations <ArrowRight className="h-3.5 w-3.5" /></Link></Button></CardContent>
      </Card>
    </div>

    <Card className="mt-4">
      <CardHeader><CardTitle>Use the independent files on your Desktop</CardTitle><CardDescription>These files are ready for a realistic August close. In Sources, choose all seven files together.</CardDescription></CardHeader>
      <CardContent><div className="rounded-lg border border-primary/20 bg-primary/5 p-4"><div className="flex items-start gap-3"><UploadCloud className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><div><div className="text-xs font-semibold text-foreground">Folder</div><code className="mt-1 block break-all text-[11px] text-muted-foreground">C:\Users\USER\Desktop\FinTrace_Independent_Test_Data</code><p className="mt-2 text-[11px] leading-5 text-muted-foreground">Upload only the seven CSV/XLSX files. Never upload <code>expected_ground_truth.json</code>; it is a private comparison reference, not an operational source.</p></div></div></div><div className="mt-4 overflow-x-auto"><Table className="w-full min-w-[680px] text-left text-xs"><TableHeader><TableRow className="border-b border-border text-[10px] uppercase tracking-wide text-muted-foreground"><TableHead className="px-3 py-2">File</TableHead><TableHead className="px-3 py-2">FinTrace source type</TableHead><TableHead className="px-3 py-2">Purpose</TableHead><TableHead className="px-3 py-2">Important columns</TableHead></TableRow></TableHeader><TableBody>{sourceFiles.map(([file, type, purpose, columns]) => <TableRow key={file} className="border-b border-border last:border-0"><TableCell className="px-3 py-3 font-mono text-[11px] font-semibold text-foreground">{file}</TableCell><TableCell className="px-3 py-3"><Badge variant="outline">{type}</Badge></TableCell><TableCell className="px-3 py-3 text-muted-foreground">{purpose}</TableCell><TableCell className="px-3 py-3 font-mono text-[10px] text-muted-foreground">{columns}</TableCell></TableRow>)}</TableBody></Table></div><div className="mt-4 flex items-center gap-2 text-[11px] text-muted-foreground"><FileSpreadsheet className="h-4 w-4 text-primary" />The independent set contains 90 August lifecycles and 544 source records. FinTrace handles the headers and rows through the same upload, mapping, normalization, and reconciliation path as any other CSV/XLSX source.</div></CardContent>
    </Card>

    <Card className="mt-4"><CardHeader><CardTitle>Who uses which part?</CardTitle><CardDescription>Use Log out only when showing a handoff between roles.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-3">{roleGuides.map(([role, focus, detail]) => <div key={role} className="rounded-lg border border-border p-4"><div className="flex items-center justify-between gap-2"><div className="text-sm font-semibold text-foreground">{role}</div><Badge variant="outline">{role === "Controller" ? "Close owner" : role === "Finance Manager" ? "Review + approve" : "Prepare + investigate"}</Badge></div><div className="mt-2 text-xs font-medium text-primary">{focus}</div><p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p></div>)}</CardContent></Card>

    <Card className="mt-4"><CardHeader><CardTitle>A simple five-minute explanation</CardTitle></CardHeader><CardContent className="grid gap-4 text-xs leading-5 text-muted-foreground md:grid-cols-2"><div><div className="font-semibold text-foreground">1. Start with the data</div><p>“These are exports from orders, payments, settlements, invoices, refunds, inventory, and employee activity. They do not share one perfect schema.”</p><div className="mt-3 font-semibold text-foreground">2. Show the control layer</div><p>“FinTrace maps the files, reconstructs the transaction lifecycle, and reconciles what code can prove. It separates healthy records from timing differences, exceptions, and ambiguous relationships.”</p></div><div><div className="font-semibold text-foreground">3. Show one exception</div><p>“For the broken lifecycle, I can see which record is missing or mismatched, where it came from, and which financial or operational control is affected.”</p><div className="mt-3 font-semibold text-foreground">4. Show safe AI and human review</div><p>“The AI retrieves bounded evidence and proposes a structured explanation. The verifier checks the claims. If evidence is not enough, the answer stays unresolved and a human must decide.”</p></div></CardContent></Card>
  </>;
}
