"use client";

import * as React from "react";
import { ArrowRight, ChevronDown } from "lucide-react";
import { useRouter } from "next/navigation";
import { Alert, AlertDescription, AlertTitle, Button } from "@fintrace/ui";
import { sampleLogin } from "../lib/api-client";

export function LoginPage() {
  const router = useRouter(); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  async function continueToFintrace(role: "CONTROLLER" | "ANALYST" | "FINANCE_MANAGER" = "CONTROLLER") { setLoading(true); setError(null); try { const session = await sampleLogin(role); window.localStorage.setItem("fintrace.access_token", session.access_token); window.localStorage.setItem("fintrace.identity", JSON.stringify(session)); router.push("/"); } catch { setError("FinTrace could not open. Check that the API is running."); setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-background px-5 py-12"><div className="w-full max-w-[1040px] lg:grid lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:gap-20"><div className="max-w-xl"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-lg font-bold text-primary-foreground">F</div><div><div className="text-xl font-bold tracking-tight text-foreground">FinTrace</div><div className="text-[10px] font-bold uppercase tracking-[0.18em] text-muted-foreground">Financial close control</div></div></div><h1 className="mt-12 text-4xl font-bold tracking-[-0.04em] text-foreground sm:text-5xl">Close the period with clarity.</h1><p className="mt-5 max-w-lg text-base leading-7 text-muted-foreground">Review and close your financial period with the routine work handled automatically and real decisions brought forward clearly.</p><div className="mt-8 flex flex-wrap gap-6 text-xs text-muted-foreground"><span>✓ Reconciled records</span><span>✓ Evidence-backed findings</span><span>✓ Controller approval boundary</span></div></div><section className="mt-12 max-w-md rounded-2xl border border-border bg-card p-7 shadow-sm lg:mt-0"><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-muted-foreground">Welcome back</div><h2 className="mt-3 text-xl font-bold tracking-tight text-foreground">Review and close your financial period.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Continue as the controller for this sample workspace.</p>{error && <Alert variant="destructive" className="mt-5"><AlertTitle>Login unavailable</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<Button className="mt-7 h-11 w-full justify-center" onClick={() => void continueToFintrace()} disabled={loading}>{loading ? "Opening FinTrace…" : "Continue to FinTrace"}<ArrowRight className="h-4 w-4" /></Button><details className="mt-5"><summary className="flex cursor-pointer list-none items-center justify-between text-[11px] font-semibold text-muted-foreground"><span>Sample options</span><ChevronDown className="h-4 w-4" /></summary><div className="mt-3 border-t border-border pt-3"><Button type="button" variant="ghost" size="sm" className="w-full justify-start px-0 text-xs text-muted-foreground hover:text-foreground" onClick={() => void continueToFintrace("ANALYST")} disabled={loading}>Open as Analyst</Button><Button type="button" variant="ghost" size="sm" className="w-full justify-start px-0 text-xs text-muted-foreground hover:text-foreground" onClick={() => void continueToFintrace("FINANCE_MANAGER")} disabled={loading}>Open as Finance Manager</Button></div></details></section></div></main>;
}
